language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install .
  - pip install -U pytest
  - pip install coverage
  - pip install coveralls
  - pip install pytest-cov

# command to run tests
script:
  py.test -v --cov mpm.py mpm_helpers.py
after_success:
  coveralls
